### ISSUE TITLE
페어 리뷰

### ISSUE THREAD

**Issue by naeun-shin** [vjiji/react-todo-prac#1]
(리뷰할게 별로 없는 좋은 코드에요!!!)

- BEST
   * 버튼의 기능과 Input의 기능을 하나의 컴포넌트로 분리하여 만든 점이 재사용하기에 좋은 것 같습니다.
   * TodoList의 컴포넌트를 하나로 관리하여 working과 done의 기능에 맞게 리스트를 보여줄 수 있도록 재사용의 장점을 표현하여 좋습니다.
   * 기능마다의 메소드를 적절하게 만들어서 기능의 구분이 잘 됩니다.
   * 공백처리 함수를 utils의 폴더에 적절하게 만들어서 사용하신 점이 좋습니다.

- THINK
   * App.js의 파일을 조금 더 간결하게 각 기능마다 분리하여 코드를 작성하셔도 깔끔하게 보여질 것 같습니다.
   * 이벤트 핸들러 기능은 좋으나, 네이밍 컨벤션을 조금 참고하셔서 수정하신다면 더 좋은 변수명으로 사용하실 수 있으실 것 같습니다.

**Comment by vjiji** [comment]
좋은 피드백 감사합니다!
말씀하신 부분들 반영해서 리팩토링 했습니다
